# @name list
GET {{ url }}/schemas
Content-Type: application/json
Authorization: {{ token }}

###

# @name create
POST {{ url }}/schemas
Content-Type: application/json
Authorization: {{ token }}

{
  "name": "test {{ $random.uuid }}",
  "content": []
}

###

# @name by-id
GET {{ url }}/schemas/{{ schema_id}}
Content-Type: application/json
Authorization: {{ token }}

###

# @name delete
DELETE {{ url }}/schemas/{{ schema_id}}
Content-Type: application/json
Authorization: {{ token }}

###

# @name update
PATCH {{ url }}/schemas/{{ schema_id}}
Content-Type: application/json
Authorization: {{ token }}

{
  "palette": ["", "", "", "", "", "", "", "", ""]
}
