# @name schemas-list
GET http://polimane.localhost/api/schemas
Content-Type: application/json

###

# @name schemas-create
POST http://polimane.localhost/api/schemas
Content-Type: application/json

{
  "name": "test {{ $random.uuid }}",
  "content": {
    "patterns": [
      {
        "type": "linear",
        "rows": []
      }
    ]
  }
}

###

# @name schemas-by-id
GET http://polimane.localhost/api/schemas/01jr3avfvywafqwj9g534w2jtp
Content-Type: application/json

###

# @name schemas-by-id-not-found
GET http://polimane.localhost/api/schemas/unknown-id
Content-Type: application/json

###

# @name schemas-delete
DELETE http://polimane.localhost/api/schemas/01jr3avfvywafqwj9g534w2jtp
Content-Type: application/json

###

# @name schemas-update
PATCH http://polimane.localhost/api/schemas/01jr3avfvywafqwj9g534w2jtp
Content-Type: application/json

{
  "name": "test 1"
}
