import Konva from 'konva';
import { createKonvaNode } from './Node';

export * from './Stage';
export type { IKonvaNodeHolder, KonvaComponent } from './Node';
export const KonvaArc = createKonvaNode('KonvaArc', Konva.Arc);
export const KonvaArrow = createKonvaNode('KonvaArrow', Konva.Arrow);
export const KonvaCircle = createKonvaNode('KonvaCircle', Konva.Circle);
export const KonvaEllipse = createKonvaNode('KonvaEllipse', Konva.Ellipse);
export const KonvaFastLayer = createKonvaNode('KonvaFastLayer', Konva.FastLayer);
export const KonvaGroup = createKonvaNode('KonvaGroup', Konva.Group);
export const KonvaImage = createKonvaNode('KonvaImage', Konva.Image);
export const KonvaLabel = createKonvaNode('KonvaLabel', Konva.Label);
export const KonvaLayer = createKonvaNode('KonvaLayer', Konva.Layer);
export const KonvaLine = createKonvaNode('KonvaLine', Konva.Line);
export const KonvaPath = createKonvaNode('KonvaPath', Konva.Path);
export const KonvaRect = createKonvaNode('KonvaRect', Konva.Rect);
export const KonvaRegularPolygon = createKonvaNode('KonvaRegularPolygon', Konva.RegularPolygon);
export const KonvaRing = createKonvaNode('KonvaRing', Konva.Ring);
export const KonvaShape = createKonvaNode('KonvaShape', Konva.Shape);
export const KonvaSprite = createKonvaNode('KonvaSprite', Konva.Sprite);
export const KonvaStar = createKonvaNode('KonvaStar', Konva.Star);
export const KonvaTag = createKonvaNode('KonvaTag', Konva.Tag);
export const KonvaText = createKonvaNode('KonvaText', Konva.Text);
export const KonvaTextPath = createKonvaNode('KonvaTextPath', Konva.TextPath);
export const KonvaTransformer = createKonvaNode('KonvaTransformer', Konva.Transformer);
export const KonvaWedge = createKonvaNode('KonvaWedge', Konva.Wedge);
