FROM polimane-prod-frontend

WORKDIR /app

ARG CLOUDFLARE_ACCOUNT_ID
ENV CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID

ARG PROJECT_NAME
ENV PROJECT_NAME=$PROJECT_NAME

RUN --mount=type=secret,id=CLOUDFLARE_API_TOKEN,env=CLOUDFLARE_API_TOKEN bun run deploy
