export const BEAD_SIZE = 12;

export const BEAD_CIRCLE_CENTER = BEAD_SIZE / 2;
export const BEAD_CIRCLE_RADIUS = BEAD_CIRCLE_CENTER - 1;

export const BEAD_BUGLE_PADDING = BEAD_SIZE / 4;
export const BEAD_BUGLE_CORNER_RADIUS = BEAD_SIZE / 6;
